const Menu = {
  avatars: 'Avatars',
  customize: 'Customize',
  contact: 'Contact',
  login: 'Log in'
}

const Home = {
  Title: 'Get unique AI-generated avatars',
  subtitle: 'Train and customize my exclusive avatar model',
  Desc: 'All avatars are automatically generated by AI, unlimited use, no copyright restrictions.',
  btn_started: 'Customize',
  more: 'Learn more'
}
export default {
  Menu,
  Home
}
